### ISSUE TITLE
Checkbox to enable/disable anonymous access

### ISSUE THREAD

**Issue by brandonbloom** [mocleiri/github-oauth-plugin#2]
![Where the option should go](https://img.skitch.com/20110811-pfxp1wtcarimqpwpyhrwn5gnui.jpg)

**Comment by GromNaN** [comment]
+1

**Comment by brandonbloom** [comment]
I just want to clarify: I think that the current implementation only support read permissions for anonymous users? That is, if this checkbox were to exist, it would be checked and disabled (unclickable). I'm proposing that this checkbox appear and be uncheckable... probably erroring on the side of unchecked by default, instead of the current default.

**Comment by mocleiri** [comment]
I tried this in testing and it would break the build tokens, i.e. it would let any request through to invoke the build and ignore the build token.

What is the use case that you need it for?

What I have in the 0.3-SNAPSHOT version is support for the github-plugin webhook (to allow anonymous read) since it already has the checks to validate the request.

I have to solve a serialization issue but hope to have it working soon

**Comment by brandonbloom** [comment]
Honestly, I want to _disable_ anonymous access, except for the github-plugin webhook.

**Comment by mocleiri** [comment]
This change is in and contained in the 0.6 release that I just made.

The default is that anonymous read access is disabled but now there is a checkbox incase anonymous reads are ok.
